# Generated by Django 5.2.9 on 2026-03-08 17:25

import django.db.models.deletion
import django.utils.timezone
import modules.base.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0006_currencyrate_rate_inverse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('active', models.BooleanField(default=True, help_text='Whether this item is active and should be displayed', verbose_name='Active')),
                ('key', models.CharField(blank=True, help_text="Unique identifier for this record like 'contact_1'", max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('destination', models.CharField(blank=True, choices=[('phi_phi', 'Phi Phi'), ('james_bond', 'James Bond'), ('krabi_from_phuket', 'Krabi from Phuket'), ('krabi_from_krabi', 'Krabi from Krabi'), ('phang_nga', 'Phang Nga'), ('phuket', 'Phuket'), ('raya_coral', 'Raya & Coral'), ('similan', 'Similan'), ('bangkok', 'Bangkok'), ('koh_samui', 'Koh Samui')], max_length=50, null=True, verbose_name='Destination')),
                ('motion_sickness', models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('extreme', 'Extreme')], max_length=20, null=True, verbose_name='Motion Sickness')),
                ('weather_sensitivity', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('extreme', 'Extreme')], max_length=20, null=True, verbose_name='Weather Sensitivity')),
                ('children_eligibility', models.CharField(blank=True, choices=[('1+', '1+'), ('3+', '3+'), ('8+', '8+'), ('12+', '12+'), ('16+', '16+'), ('conditional', 'Conditional')], max_length=20, null=True, verbose_name='Children Eligibility')),
                ('action_adrenaline', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True, verbose_name='Action Adrenaline')),
                ('romantic_honeymoon', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True, verbose_name='Romantic / Honeymoon')),
                ('smoker_friendly', models.CharField(blank=True, choices=[('allowed', 'Allowed'), ('conditional', 'Conditional')], max_length=20, null=True, verbose_name='Smoker Friendly')),
                ('price_range', models.CharField(blank=True, choices=[('<2000', '<2000 THB'), ('2000-3500', '2000-3500 THB'), ('>3500', '>3500 THB')], max_length=20, null=True, verbose_name='Price Range')),
                ('lunch', models.CharField(blank=True, choices=[('none', 'None'), ('island', 'Island'), ('onboard', 'Onbaord'), ('restaurant', 'Rest.'), ('extra', 'Extra')], max_length=20, null=True, verbose_name='Lunch')),
                ('stop_activity', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('9+', '9+'), ('custom', 'Custom')], max_length=10, null=True, verbose_name='Stop/Activity')),
                ('duration', models.CharField(blank=True, choices=[('3_hours', '3 Hours'), ('half_day', 'Half Day'), ('full_day', 'Full Day'), ('custom', 'Custom')], max_length=20, null=True, verbose_name='Duration')),
                ('time', models.CharField(blank=True, choices=[('early_morning', 'Early Morning'), ('early_bird', 'Early Bird'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('flexible', 'Flexible'), ('overnight', 'Overnight')], max_length=20, null=True, verbose_name='Time')),
                ('activity_type', models.CharField(blank=True, choices=[('sea_trip', 'Sea Trip'), ('sea_adventure', 'Sea Adv.'), ('water_activity', 'Water Act.'), ('river_adventure', 'River Adv.'), ('land_adventure', 'Land Adv.'), ('evening_show', 'Evening Show'), ('city_tour', 'City Tour')], max_length=20, null=True, verbose_name='Activity Type')),
                ('quality', models.CharField(blank=True, choices=[('economy', 'Economy'), ('average', 'Average'), ('conditional', 'Conditional'), ('premium', 'Premium'), ('high_end', 'High End'), ('luxury', 'Luxury'), ('private', 'Private')], max_length=20, null=True, verbose_name='Quality')),
                ('service_onboard', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True, verbose_name='Service Onboard')),
                ('stability', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True, verbose_name='Stability')),
                ('mobility', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20, null=True, verbose_name='Mobility')),
                ('boat_view', models.CharField(blank=True, choices=[('no_view', 'No View'), ('partial', 'Partial'), ('wide', 'Wide'), ('panoramic', 'Panoramic')], max_length=20, null=True, verbose_name='Boat View')),
                ('water_activity', models.CharField(blank=True, choices=[('none', 'None'), ('basic', 'Basic'), ('extra', 'Extra'), ('multiple', 'Multiple')], max_length=20, null=True, verbose_name='Water Activity')),
                ('no_of_pax', models.CharField(blank=True, choices=[('<30', '<30'), ('30-60', '30-60'), ('>60', '>60')], max_length=10, null=True, verbose_name='No. of PAX')),
                ('longtail_boat', models.CharField(blank=True, choices=[('none', 'None'), ('excluded', 'Excluded'), ('included', 'Included'), ('zodiac', 'Zodiac')], max_length=20, null=True, verbose_name='Longtail Boat')),
                ('national_park', models.CharField(blank=True, choices=[('extra_200', 'Extra 200'), ('extra_300', 'Extra 300'), ('extra_400', 'Extra 400'), ('extra_500', 'Extra 500'), ('extra_600', 'Extra 600'), ('included', 'Included')], max_length=20, null=True, verbose_name='National Park')),
                ('sell_prc_adult', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sell PRC Ad.')),
                ('net_prc_adult', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net PRC Ad.')),
                ('sell_prc_child', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sell PRC Ch.')),
                ('net_prc_child', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Net PRC Ch.')),
                ('min_markup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min. Markup')),
                ('whatsapp_catalog_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='WhatsApp Catalog Link')),
                ('video_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Video Link')),
                ('album', models.CharField(blank=True, max_length=255, null=True, verbose_name='Album')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('audio_ar', modules.base.fields.AttachmentManyToManyField(allowed_types=['audio'], blank=True, related_name='availabletrip_audio_ar', related_query_name='availabletrip_audio_ar', to='base.attachment', upload_to='yalla_thailand/trips/audio_ar', verbose_name='Audio (AR)')),
                ('audio_en', modules.base.fields.AttachmentManyToManyField(allowed_types=['audio'], blank=True, related_name='availabletrip_audio_en', related_query_name='availabletrip_audio_en', to='base.attachment', upload_to='yalla_thailand/trips/audio_en', verbose_name='Audio (EN)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('main_image', modules.base.fields.AttachmentForeignKeyField(allowed_types=['image'], blank=True, help_text='Main image for the trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_attachment_relations', to='base.attachment', upload_to='yalla_thailand/trips/')),
                ('pics_ar', modules.base.fields.AttachmentManyToManyField(allowed_types=['image'], blank=True, related_name='availabletrip_pics_ar', related_query_name='availabletrip_pics_ar', to='base.attachment', upload_to='yalla_thailand/trips/pics_ar', verbose_name='Pictures (AR)')),
                ('pics_en', modules.base.fields.AttachmentManyToManyField(allowed_types=['image'], blank=True, related_name='availabletrip_pics_en', related_query_name='availabletrip_pics_en', to='base.attachment', upload_to='yalla_thailand/trips/pics_en', verbose_name='Pictures (EN)')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yalla_supplied_trips', to='base.partner', verbose_name='Supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified_by_related', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('video_ar', modules.base.fields.AttachmentManyToManyField(allowed_types=['video'], blank=True, related_name='availabletrip_video_ar', related_query_name='availabletrip_video_ar', to='base.attachment', upload_to='yalla_thailand/trips/video_ar', verbose_name='Video (AR)')),
                ('video_en', modules.base.fields.AttachmentManyToManyField(allowed_types=['video'], blank=True, related_name='availabletrip_video_en', related_query_name='availabletrip_video_en', to='base.attachment', upload_to='yalla_thailand/trips/video_en', verbose_name='Video (EN)')),
            ],
            options={
                'verbose_name': 'Available Trip',
                'verbose_name_plural': 'Available Trips',
            },
        ),
    ]
