# Generated by Django 5.2.9 on 2026-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yalla_thailand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletrip',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
